using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace BusinessLogic.Enums.Types;

[JsonConverter(typeof(StringEnumConverter))]
public enum Color
{
    Aquamarine,
    Azure,
    Black,
    Blue,
    Blurple,
    Brown,
    Chartreuse,
    CornflowerBlue,
    Cyan,
    DarkBlue,
    DarkButNotBlack,
    DarkGray,
    DarkGreen,
    DarkRed,
    Gold,
    Goldenrod,
    Gray,
    Grayple,
    Green,
    HotPink,
    IndianRed,
    LightGray,
    Lilac,
    Magenta,
    MidnightBlue,
    NotQuiteBlack,
    Orange,
    PhthaloBlue,
    PhthaloGreen,
    Purple,
    Red,
    Rose,
    SapGreen,
    Sienna,
    SpringGreen,
    Teal,
    Turquoise,
    VeryDarkGray,
    Violet,
    Wheat,
    White,
    Yellow,
}
